name: build
on:
  push:
    branches: [main]
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm i typescript typedoc
      - run: cp readme.md docs/
      - run: npx typedoc --out docs/api --skipErrorChecking src
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
